export type ApiCategory = 'internal_trpc' | 'external_data' | 'ai_inference' | 'infrastructure';

export type ApiStatus = 'implemented' | 'partial' | 'missing' | 'planned';

export type ApiMethod = 'query' | 'mutation' | 'GET' | 'POST';

export interface ApiAuthDetails {
  type: 'none' | 'apiKey' | 'bearer';
  environmentVariables: string[];
  notes?: string;
}

export interface ApiEndpoint {
  key: string;
  name: string;
  description: string;
  category: ApiCategory;
  implementationStatus: ApiStatus;
  route?: string;
  method?: ApiMethod;
  filePath: string;
  auth: ApiAuthDetails;
  externalBaseUrl?: string;
  dependencies: string[];
  remarks?: string;
}

export const apiCatalog: ApiEndpoint[] = [
  {
    key: 'trpc.example.hi',
    name: 'Example Greeting',
    description: 'Health check route returning greeting and timestamp',
    category: 'internal_trpc',
    implementationStatus: 'implemented',
    route: 'example.hi',
    method: 'query',
    filePath: 'backend/trpc/routes/example/hi/route.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'No authentication implemented in create-context.ts',
    },
    dependencies: ['backend/trpc/create-context.ts'],
    remarks: 'Should be removed or secured before production',
  },
  {
    key: 'trpc.products.getByBarcode',
    name: 'Product Lookup by Barcode',
    description: 'Returns product details from cache or external sources for a given barcode',
    category: 'internal_trpc',
    implementationStatus: 'partial',
    route: 'products.getByBarcode',
    method: 'query',
    filePath: 'backend/trpc/routes/products/getByBarcode.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'Lacks user-level authorization and rate limiting',
    },
    dependencies: ['backend/services/productService.ts', 'backend/db/schema.ts'],
    remarks: 'Depends on multiple external product databases; skips sources without API keys',
  },
  {
    key: 'trpc.products.search',
    name: 'Product Search',
    description: 'Performs keyword search against Open Food Facts',
    category: 'internal_trpc',
    implementationStatus: 'implemented',
    route: 'products.search',
    method: 'query',
    filePath: 'backend/trpc/routes/products/search.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'Unauthenticated endpoint that exposes search functionality publicly',
    },
    dependencies: ['backend/services/productService.ts'],
    remarks: 'Limited to Open Food Facts result set and subject to their availability',
  },
  {
    key: 'trpc.products.popular',
    name: 'Popular Products',
    description: 'Returns products ordered by scan counts from local cache',
    category: 'internal_trpc',
    implementationStatus: 'implemented',
    route: 'products.popular',
    method: 'query',
    filePath: 'backend/trpc/routes/products/popular.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'Pulls from AsyncStorage cache without user scoping',
    },
    dependencies: ['backend/services/productService.ts', 'backend/db/schema.ts'],
    remarks: 'Returns global data; needs per-user or per-tenant segregation',
  },
  {
    key: 'trpc.products.recent',
    name: 'Recent Products',
    description: 'Returns recently fetched products from cache',
    category: 'internal_trpc',
    implementationStatus: 'implemented',
    route: 'products.recent',
    method: 'query',
    filePath: 'backend/trpc/routes/products/recent.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'AsyncStorage cache shared across users',
    },
    dependencies: ['backend/services/productService.ts', 'backend/db/schema.ts'],
    remarks: 'Needs eviction and user scoping improvements',
  },
  {
    key: 'trpc.recalls.search',
    name: 'Recall Search',
    description: 'Searches FDA recall database using keyword query',
    category: 'internal_trpc',
    implementationStatus: 'implemented',
    route: 'recalls.search',
    method: 'query',
    filePath: 'backend/trpc/routes/recalls/search.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'No auth or abuse throttling in place',
    },
    dependencies: ['backend/services/recallService.ts'],
    remarks: 'Limited to food recalls; no support for cosmetics or medical devices',
  },
  {
    key: 'trpc.recalls.searchByBarcode',
    name: 'Recall Search by Barcode',
    description: 'Matches recalls against product barcode text',
    category: 'internal_trpc',
    implementationStatus: 'implemented',
    route: 'recalls.searchByBarcode',
    method: 'query',
    filePath: 'backend/trpc/routes/recalls/searchByBarcode.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'Exposes FDA queries without authentication',
    },
    dependencies: ['backend/services/recallService.ts'],
    remarks: 'Barcode search is fragile because FDA descriptions rarely contain barcode numbers',
  },
  {
    key: 'trpc.analytics.track',
    name: 'Analytics Event Tracking',
    description: 'Persists user activity events into AsyncStorage-backed analytics log',
    category: 'internal_trpc',
    implementationStatus: 'partial',
    route: 'analytics.track',
    method: 'mutation',
    filePath: 'backend/trpc/routes/analytics/track.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'Allows spoofed userId because authentication is absent',
    },
    dependencies: ['backend/services/analyticsService.ts', 'backend/db/schema.ts'],
    remarks: 'Needs authenticated context and batching to real analytics sink',
  },
  {
    key: 'trpc.analytics.stats',
    name: 'Analytics Summary',
    description: 'Aggregates stored analytics events for dashboards',
    category: 'internal_trpc',
    implementationStatus: 'partial',
    route: 'analytics.stats',
    method: 'query',
    filePath: 'backend/trpc/routes/analytics/stats.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'Users can query any userId without authorization',
    },
    dependencies: ['backend/services/analyticsService.ts'],
    remarks: 'Accuracy limited by local storage persistence and device scope',
  },
  {
    key: 'trpc.profiles.list',
    name: 'Profile List',
    description: 'Returns allergy profiles for a user from AsyncStorage',
    category: 'internal_trpc',
    implementationStatus: 'partial',
    route: 'profiles.list',
    method: 'query',
    filePath: 'backend/trpc/routes/profiles/list.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'Relies on userId provided by client without verification',
    },
    dependencies: ['backend/db/schema.ts'],
    remarks: 'Needs authentication and multi-device sync',
  },
  {
    key: 'trpc.profiles.create',
    name: 'Create Profile',
    description: 'Creates a new allergy profile and persists it locally',
    category: 'internal_trpc',
    implementationStatus: 'partial',
    route: 'profiles.create',
    method: 'mutation',
    filePath: 'backend/trpc/routes/profiles/create.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'Allows unauthenticated profile creation for any userId',
    },
    dependencies: ['backend/db/schema.ts'],
    remarks: 'Must enforce user ownership and server-side validation',
  },
  {
    key: 'trpc.profiles.update',
    name: 'Update Profile',
    description: 'Updates existing allergy profile data',
    category: 'internal_trpc',
    implementationStatus: 'partial',
    route: 'profiles.update',
    method: 'mutation',
    filePath: 'backend/trpc/routes/profiles/update.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'No authorization guard on profile ownership',
    },
    dependencies: ['backend/db/schema.ts'],
    remarks: 'Requires optimistic updates and server validation hardening',
  },
  {
    key: 'trpc.profiles.delete',
    name: 'Delete Profile',
    description: 'Deletes an allergy profile by id',
    category: 'internal_trpc',
    implementationStatus: 'partial',
    route: 'profiles.delete',
    method: 'mutation',
    filePath: 'backend/trpc/routes/profiles/delete.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'Client can delete any profile id without checks',
    },
    dependencies: ['backend/db/schema.ts'],
    remarks: 'Needs server-side ownership checks and audit logging',
  },
  {
    key: 'trpc.data.export',
    name: 'Export Local Data',
    description: 'Exports AsyncStorage datasets as JSON',
    category: 'internal_trpc',
    implementationStatus: 'implemented',
    route: 'data.export',
    method: 'query',
    filePath: 'backend/trpc/routes/data/export.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'Potentially exposes sensitive user data without auth',
    },
    dependencies: ['backend/db/schema.ts'],
    remarks: 'Needs authentication and encryption before production use',
  },
  {
    key: 'trpc.data.import',
    name: 'Import Local Data',
    description: 'Imports JSON payload into AsyncStorage datasets',
    category: 'internal_trpc',
    implementationStatus: 'implemented',
    route: 'data.import',
    method: 'mutation',
    filePath: 'backend/trpc/routes/data/import.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'No payload validation or auth; high risk for data corruption',
    },
    dependencies: ['backend/db/schema.ts'],
    remarks: 'Requires schema validation and auth before production',
  },
  {
    key: 'external.openFoodFacts',
    name: 'Open Food Facts API',
    description: 'Primary open dataset for global food product information',
    category: 'external_data',
    implementationStatus: 'implemented',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
    },
    externalBaseUrl: 'https://world.openfoodfacts.org/api/v2',
    dependencies: ['api/products.ts', 'backend/services/productService.ts'],
    remarks: 'Provides limited cosmetic data and can be stale for niche products',
  },
  {
    key: 'external.openBeautyFacts',
    name: 'Open Beauty Facts API',
    description: 'Open dataset for cosmetic and skincare product details',
    category: 'external_data',
    implementationStatus: 'implemented',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
    },
    externalBaseUrl: 'https://world.openbeautyfacts.org/api/v2',
    dependencies: ['api/products.ts', 'backend/services/productService.ts'],
    remarks: 'Coverage is inconsistent and often lacks ingredient breakdowns',
  },
  {
    key: 'external.openProductsFacts',
    name: 'Open Products Facts API',
    description: 'Supplemental open dataset for non-food products',
    category: 'external_data',
    implementationStatus: 'implemented',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
    },
    externalBaseUrl: 'https://world.openproductsfacts.org/api/v2',
    dependencies: ['api/products.ts', 'backend/services/productService.ts'],
    remarks: 'Data completeness is low; consider premium product intelligence sources',
  },
  {
    key: 'external.upcDatabase',
    name: 'UPC Database API',
    description: 'UPC lookup service returning basic product metadata',
    category: 'external_data',
    implementationStatus: 'partial',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'API terms usually require registered token; current integration unauthenticated',
    },
    externalBaseUrl: 'https://api.upcdatabase.org/product',
    dependencies: ['api/products.ts', 'backend/services/productService.ts'],
    remarks: 'Responses can be rate limited or blocked without proper API key',
  },
  {
    key: 'external.upcItemDb',
    name: 'UPCItemDB API',
    description: 'Trial product lookup API used as fallback source',
    category: 'external_data',
    implementationStatus: 'implemented',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
      notes: 'Trial endpoint with strict rate limits',
    },
    externalBaseUrl: 'https://api.upcitemdb.com/prod/trial/lookup',
    dependencies: ['api/products.ts', 'backend/services/productService.ts'],
    remarks: 'Requires commercial plan for reliable production access',
  },
  {
    key: 'external.barcodeLookup',
    name: 'Barcode Lookup API',
    description: 'Commercial product database with rich metadata and images',
    category: 'external_data',
    implementationStatus: 'missing',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'apiKey',
      environmentVariables: ['BARCODE_LOOKUP_KEY'],
      notes: 'Integration skipped at runtime when key is absent',
    },
    externalBaseUrl: 'https://api.barcodelookup.com/v3/products',
    dependencies: ['backend/services/productService.ts'],
    remarks: 'Key not provisioned; enabling would improve coverage and accuracy',
  },
  {
    key: 'external.worldUpc',
    name: 'WorldUPC API',
    description: 'Premium UPC database with manufacturer information',
    category: 'external_data',
    implementationStatus: 'missing',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'bearer',
      environmentVariables: ['WORLD_UPC_API_KEY'],
      notes: 'Requests skipped because auth token is undefined',
    },
    externalBaseUrl: 'https://api.worldupc.com/api/v2',
    dependencies: ['backend/services/productService.ts'],
    remarks: 'Required for comprehensive UPC coverage and manufacturer verification',
  },
  {
    key: 'external.eanSearch',
    name: 'EAN Search API',
    description: 'Lightweight EAN lookup endpoint returning basic product names',
    category: 'external_data',
    implementationStatus: 'implemented',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
    },
    externalBaseUrl: 'https://ean-search.org/api',
    dependencies: ['api/products.ts', 'backend/services/productService.ts'],
    remarks: 'Returns minimal data and frequently responds with HTML errors',
  },
  {
    key: 'external.datakick',
    name: 'DataKick API',
    description: 'Community barcode database used as fallback',
    category: 'external_data',
    implementationStatus: 'implemented',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
    },
    externalBaseUrl: 'https://www.datakick.org/api/items',
    dependencies: ['api/products.ts', 'backend/services/productService.ts'],
    remarks: 'Open API with reliability concerns; lacks cosmetics data',
  },
  {
    key: 'external.usda',
    name: 'USDA FoodData Central',
    description: 'Government nutrition database accessed as fallback',
    category: 'external_data',
    implementationStatus: 'partial',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'apiKey',
      environmentVariables: ['USDA_API_KEY'],
      notes: 'Falls back to DEMO_KEY which is heavily rate limited',
    },
    externalBaseUrl: 'https://api.nal.usda.gov/fdc/v1',
    dependencies: ['api/products.ts', 'backend/services/productService.ts'],
    remarks: 'Requires paid key for production throughput and reliability',
  },
  {
    key: 'external.nutritionix',
    name: 'Nutritionix API',
    description: 'Branded food nutrition database for UPC lookups',
    category: 'external_data',
    implementationStatus: 'missing',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'apiKey',
      environmentVariables: ['NUTRITIONIX_APP_ID', 'NUTRITIONIX_APP_KEY'],
      notes: 'Integration disabled when credentials are absent',
    },
    externalBaseUrl: 'https://trackapi.nutritionix.com/v2',
    dependencies: ['backend/services/productService.ts'],
    remarks: 'Needed for packaged food nutrition facts and allergen flags',
  },
  {
    key: 'external.edamam',
    name: 'Edamam Food Database',
    description: 'Commercial API for ingredient level nutrition and allergens',
    category: 'external_data',
    implementationStatus: 'missing',
    method: 'GET',
    filePath: 'backend/services/productService.ts',
    auth: {
      type: 'apiKey',
      environmentVariables: ['EDAMAM_APP_ID', 'EDAMAM_APP_KEY'],
      notes: 'Requests skipped when keys are undefined',
    },
    externalBaseUrl: 'https://api.edamam.com/api/food-database/v2',
    dependencies: ['backend/services/productService.ts'],
    remarks: 'Would supply macronutrients and ingredient parsing needed for premium experience',
  },
  {
    key: 'external.fdaRecalls',
    name: 'FDA Food Enforcement API',
    description: 'Public API for food recall notices',
    category: 'external_data',
    implementationStatus: 'implemented',
    method: 'GET',
    filePath: 'backend/services/recallService.ts',
    auth: {
      type: 'none',
      environmentVariables: [],
    },
    externalBaseUrl: 'https://api.fda.gov/food/enforcement.json',
    dependencies: ['api/recalls.ts', 'backend/services/recallService.ts'],
    remarks: 'Only covers US food recalls; lacks cosmetics, drugs, and international recalls',
  },
  {
    key: 'ai.rorkToolkit.generateText',
    name: 'Rork Toolkit Text Generation',
    description: 'LLM endpoint used for photo analysis and safe swap recommendations',
    category: 'ai_inference',
    implementationStatus: 'implemented',
    method: 'POST',
    filePath: 'services/safeSwapService.ts',
    auth: {
      type: 'bearer',
      environmentVariables: ['EXPO_PUBLIC_TOOLKIT_URL'],
      notes: 'Falls back to https://toolkit.rork.com when env is missing',
    },
    externalBaseUrl: 'https://toolkit.rork.com',
    dependencies: ['app/(tabs)/(scan)/index.tsx', 'services/safeSwapService.ts', 'app/product/[code].tsx'],
    remarks: 'Requires latency monitoring and guardrails for hallucinations',
  },
  {
    key: 'infrastructure.trpcTransport',
    name: 'tRPC HTTP Transport',
    description: 'Fetch-based transport linking Expo client to Hono backend',
    category: 'infrastructure',
    implementationStatus: 'implemented',
    method: 'POST',
    filePath: 'lib/trpc.ts',
    auth: {
      type: 'none',
      environmentVariables: ['EXPO_PUBLIC_RORK_API_BASE_URL'],
      notes: 'Backend disabled when base URL is undefined',
    },
    externalBaseUrl: '/api/trpc',
    dependencies: ['app/_layout.tsx', 'hooks/useLiveData.ts'],
    remarks: 'Needs secure session handling and retry strategy for Already read errors',
  },
  {
    key: 'external.inciDirectory',
    name: 'Planned Cosmetic Ingredient Directory',
    description: 'Third-party INCI database required for complete skincare ingredient lists',
    category: 'external_data',
    implementationStatus: 'planned',
    method: 'GET',
    filePath: 'N/A',
    auth: {
      type: 'apiKey',
      environmentVariables: ['INCI_API_KEY'],
      notes: 'Not yet integrated; needed to prevent mismatched safe swap results',
    },
    externalBaseUrl: 'https://api.inci-dictionary.com',
    dependencies: [],
    remarks: 'Would enable accurate hydration mask ingredient retrieval and classification',
  },
  {
    key: 'external.globalRecall',
    name: 'Planned Global Recall Aggregator',
    description: 'API for cosmetics and international recalls to supplement FDA data',
    category: 'external_data',
    implementationStatus: 'missing',
    method: 'GET',
    filePath: 'N/A',
    auth: {
      type: 'apiKey',
      environmentVariables: ['GLOBAL_RECALL_API_KEY'],
      notes: 'Required for best-in-class safety coverage',
    },
    externalBaseUrl: 'https://api.globalrecallsafety.com/v1',
    dependencies: [],
    remarks: 'Needed to surface skincare recalls and non-US alerts mentioned in user requirements',
  },
  {
    key: 'external.retailerInventory',
    name: 'Planned Retailer Inventory API',
    description: 'Retail availability and pricing feed for safe swap recommendations',
    category: 'external_data',
    implementationStatus: 'missing',
    method: 'GET',
    filePath: 'N/A',
    auth: {
      type: 'apiKey',
      environmentVariables: ['RETAILER_API_KEY'],
      notes: 'Required to provide store-level availability in AI suggestions',
    },
    externalBaseUrl: 'https://api.retailer.com/v1',
    dependencies: [],
    remarks: 'Supports user expectation for actionable alternatives with real store data',
  },
  {
    key: 'infrastructure.auth',
    name: 'Authentication Provider',
    description: 'Missing auth service to secure tRPC endpoints and associate data with users',
    category: 'infrastructure',
    implementationStatus: 'missing',
    method: 'POST',
    filePath: 'N/A',
    auth: {
      type: 'bearer',
      environmentVariables: ['AUTH_SECRET', 'AUTH_BASE_URL'],
      notes: 'No authentication implementation present',
    },
    externalBaseUrl: 'https://auth.example.com',
    dependencies: ['backend/trpc/create-context.ts'],
    remarks: 'Essential for production readiness and to prevent unauthorized data access',
  }
];