import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Platform, Alert } from 'react-native';
import { AlertCircle, Phone, Pill, Share2, QrCode, ScanLine } from 'lucide-react-native';
import { useProfiles } from '@/contexts/ProfileContext';
import { Stack, router } from 'expo-router';
import QRCode from 'react-native-qrcode-svg';

export default function EmergencyCardScreen() {
  const { activeProfile } = useProfiles();

  const generateQRData = () => {
    if (!activeProfile) return '';
    
    const emergencyData = {
      type: 'EMERGENCY_ALLERGY_CARD',
      version: '1.0',
      name: activeProfile.name,
      allergens: activeProfile.allergens,
      hasAnaphylaxis: activeProfile.hasAnaphylaxis,
      medications: activeProfile.medications,
      emergencyContacts: activeProfile.emergencyContacts,
      dateOfBirth: activeProfile.dateOfBirth,
      relationship: activeProfile.relationship,
      generatedAt: new Date().toISOString(),
    };
    
    return JSON.stringify(emergencyData);
  };

  const handleShareProfile = async () => {
    if (!activeProfile) return;
    
    try {
      const allergensList = activeProfile.allergens.join(', ');
      const medicationsList = activeProfile.medications.length > 0 
        ? `\n\nMedications:\n${activeProfile.medications.map(m => `• ${m}`).join('\n')}`
        : '';
      const contactsList = activeProfile.emergencyContacts.length > 0
        ? `\n\nEmergency Contacts:\n${activeProfile.emergencyContacts.map(c => `• ${c.name} (${c.relationship}): ${c.phone}`).join('\n')}`
        : '';
      const anaphylaxisWarning = activeProfile.hasAnaphylaxis 
        ? '\n\n⚠️ RISK OF ANAPHYLAXIS - Carry epinephrine auto-injector'
        : '';
      
      const message = `🚨 EMERGENCY ALLERGY CARD\n\nName: ${activeProfile.name}\n\nALLERGIC TO:\n${allergensList}${anaphylaxisWarning}${medicationsList}${contactsList}\n\nIn case of severe reaction:\n1. Administer epinephrine if prescribed\n2. Call 911 immediately\n3. Keep person lying down (unless vomiting)\n\nGenerated by Allergy Guardian`;
      
      if (Platform.OS === 'web') {
        if (navigator.share) {
          await navigator.share({
            title: `${activeProfile.name} - Emergency Allergy Card`,
            text: message,
          });
        } else {
          await navigator.clipboard.writeText(message);
          Alert.alert('Copied!', 'Emergency card information copied to clipboard');
        }
      } else {
        const Share = require('react-native').Share;
        await Share.share({
          message: message,
          title: `${activeProfile.name} - Emergency Allergy Card`,
        });
      }
    } catch (error: any) {
      if (error?.message !== 'User did not share') {
        console.error('Error sharing:', error);
      }
    }
  };

  if (!activeProfile) {
    return (
      <View style={styles.centerContainer}>
        <AlertCircle size={64} color="#9CA3AF" />
        <Text style={styles.emptyText}>No active profile</Text>
      </View>
    );
  }

  return (
    <>
      <Stack.Screen 
        options={{ 
          title: 'Emergency Card',
          headerRight: () => (
            <TouchableOpacity onPress={handleShareProfile} style={{ marginRight: 16 }}>
              <Share2 size={24} color="#6B7280" />
            </TouchableOpacity>
          ),
        }} 
      />
      <ScrollView style={styles.container} contentContainerStyle={styles.scrollContent}>
      <View style={styles.emergencyHeader}>
        <AlertCircle size={48} color="#DC2626" />
        <Text style={styles.emergencyTitle}>EMERGENCY CARD</Text>
      </View>

      <View style={styles.qrContainer}>
        <View style={styles.qrCodeWrapper}>
          <QRCode
            value={generateQRData()}
            size={280}
            backgroundColor="white"
            color="#111827"
            logo={require('@/assets/images/icon.png')}
            logoSize={50}
            logoBackgroundColor="white"
            logoBorderRadius={10}
          />
        </View>
        <View style={styles.qrInfo}>
          <QrCode size={20} color="#6B7280" />
          <Text style={styles.qrInfoText}>Scan this QR code in an emergency</Text>
        </View>
      </View>

      <View style={styles.card}>
        <Text style={styles.cardTitle}>ALLERGY ALERT</Text>
        <Text style={styles.profileName}>{activeProfile.name}</Text>
        
        <View style={styles.section}>
          <Text style={styles.sectionLabel}>ALLERGIC TO:</Text>
          <View style={styles.allergenList}>
            {activeProfile.allergens.map((allergen, index) => (
              <View key={index} style={styles.allergenBadge}>
                <Text style={styles.allergenText}>{allergen}</Text>
              </View>
            ))}
          </View>
        </View>

        {activeProfile.hasAnaphylaxis && (
          <View style={styles.warningBox}>
            <AlertCircle size={24} color="#DC2626" />
            <Text style={styles.warningText}>RISK OF ANAPHYLAXIS</Text>
          </View>
        )}
      </View>

      {activeProfile.medications.length > 0 && (
        <View style={styles.card}>
          <View style={styles.cardHeader}>
            <Pill size={24} color="#0891B2" />
            <Text style={styles.cardTitle}>MEDICATIONS</Text>
          </View>
          {activeProfile.medications.map((med, index) => (
            <View key={index} style={styles.medicationItem}>
              <Text style={styles.medicationText}>{med}</Text>
            </View>
          ))}
        </View>
      )}

      {activeProfile.emergencyContacts.length > 0 && (
        <View style={styles.card}>
          <View style={styles.cardHeader}>
            <Phone size={24} color="#0891B2" />
            <Text style={styles.cardTitle}>EMERGENCY CONTACTS</Text>
          </View>
          {activeProfile.emergencyContacts.map((contact, index) => (
            <View key={index} style={styles.contactItem}>
              <Text style={styles.contactName}>{contact.name}</Text>
              <Text style={styles.contactRelationship}>{contact.relationship}</Text>
              <Text style={styles.contactPhone}>{contact.phone}</Text>
            </View>
          ))}
        </View>
      )}

      <View style={styles.instructionsCard}>
        <Text style={styles.instructionsTitle}>IN CASE OF SEVERE REACTION:</Text>
        <View style={styles.instructionsList}>
          <Text style={styles.instructionItem}>1. Administer epinephrine if prescribed</Text>
          <Text style={styles.instructionItem}>2. Call 911 immediately</Text>
          <Text style={styles.instructionItem}>3. Contact emergency contacts</Text>
          <Text style={styles.instructionItem}>4. Keep person lying down (unless vomiting)</Text>
          <Text style={styles.instructionItem}>5. Second dose may be needed after 5-15 minutes</Text>
        </View>
      </View>

      <View style={styles.disclaimer}>
        <Text style={styles.disclaimerText}>
          This card is for informational purposes only. Always follow medical professional guidance and prescribed treatment plans.
        </Text>
      </View>
      
      <TouchableOpacity
        style={styles.shareButton}
        onPress={handleShareProfile}
      >
        <Share2 size={24} color="#FFFFFF" />
        <Text style={styles.shareButtonText}>Share Emergency Card</Text>
      </TouchableOpacity>

      <TouchableOpacity
        style={styles.scanButton}
        onPress={() => router.push('/scan-emergency-qr')}
      >
        <ScanLine size={24} color="#0891B2" />
        <Text style={styles.scanButtonText}>Scan Someone&apos;s Emergency QR</Text>
      </TouchableOpacity>
    </ScrollView>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#F9FAFB',
  },
  scrollContent: {
    padding: 16,
  },
  emergencyHeader: {
    alignItems: 'center',
    backgroundColor: '#FEE2E2',
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
    borderWidth: 3,
    borderColor: '#DC2626',
  },
  emergencyTitle: {
    fontSize: 28,
    fontWeight: '700' as const,
    color: '#DC2626',
    marginTop: 12,
    letterSpacing: 2,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#111827',
    letterSpacing: 1,
  },
  profileName: {
    fontSize: 32,
    fontWeight: '700' as const,
    color: '#111827',
    marginBottom: 24,
  },
  section: {
    marginBottom: 16,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#6B7280',
    marginBottom: 12,
    letterSpacing: 1,
  },
  allergenList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  allergenBadge: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#DC2626',
  },
  allergenText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: '#DC2626',
  },
  warningBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FEE2E2',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#DC2626',
  },
  warningText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: '#DC2626',
    letterSpacing: 1,
  },
  medicationItem: {
    backgroundColor: '#F0FDFA',
    padding: 16,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#0891B2',
  },
  medicationText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#111827',
  },
  contactItem: {
    backgroundColor: '#F9FAFB',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  contactName: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#111827',
    marginBottom: 4,
  },
  contactRelationship: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 4,
  },
  contactPhone: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#0891B2',
  },
  instructionsCard: {
    backgroundColor: '#FEF3C7',
    borderRadius: 16,
    padding: 24,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#F59E0B',
  },
  instructionsTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#92400E',
    marginBottom: 16,
    letterSpacing: 1,
  },
  instructionsList: {
    gap: 12,
  },
  instructionItem: {
    fontSize: 16,
    color: '#92400E',
    lineHeight: 24,
  },
  disclaimer: {
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 16,
  },
  disclaimerText: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 18,
  },
  emptyText: {
    fontSize: 20,
    fontWeight: '600' as const,
    color: '#111827',
    marginTop: 16,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#0891B2',
    borderRadius: 16,
    padding: 20,
    marginTop: 16,
    marginBottom: 32,
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  shareButtonText: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#FFFFFF',
  },
  qrContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#DC2626',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  qrCodeWrapper: {
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginBottom: 16,
  },
  qrInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
  },
  qrInfoText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#6B7280',
  },
  scanButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 32,
    borderWidth: 2,
    borderColor: '#0891B2',
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  scanButtonText: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#0891B2',
  },
});
