-- =============================================
-- SafeBite System Health & Auto-Remediation Tables
-- Migration for self-scan, monitoring, and audit trail
-- =============================================

-- =============================================
-- 1. SYSTEM HEALTH RUNS
-- Main table tracking each health check execution
-- =============================================
CREATE TABLE IF NOT EXISTS public.system_health_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMP WITH TIME ZONE,
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'pass', 'warn', 'fail')),
  environment TEXT NOT NULL DEFAULT 'production' CHECK (environment IN ('development', 'preview', 'production')),
  app_version TEXT,
  trigger_type TEXT NOT NULL DEFAULT 'scheduled' CHECK (trigger_type IN ('scheduled', 'manual', 'webhook')),
  triggered_by UUID REFERENCES auth.users(id),
  summary_text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- 2. SYSTEM HEALTH CHECKS
-- Individual check results within a run
-- =============================================
CREATE TABLE IF NOT EXISTS public.system_health_checks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id UUID NOT NULL REFERENCES public.system_health_runs(id) ON DELETE CASCADE,
  check_name TEXT NOT NULL,
  check_category TEXT NOT NULL DEFAULT 'general' CHECK (check_category IN ('auth', 'database', 'api', 'cache', 'queue', 'storage', 'external', 'general')),
  status TEXT NOT NULL CHECK (status IN ('pass', 'warn', 'fail', 'skip')),
  duration_ms INTEGER,
  details JSONB DEFAULT '{}',
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- 3. SYSTEM ACTIONS
-- Auto-remediation actions taken
-- =============================================
CREATE TABLE IF NOT EXISTS public.system_actions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id UUID REFERENCES public.system_health_runs(id) ON DELETE SET NULL,
  action_name TEXT NOT NULL,
  action_type TEXT NOT NULL DEFAULT 'remediation' CHECK (action_type IN ('remediation', 'cleanup', 'notification', 'escalation')),
  status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'success', 'failed', 'skipped')),
  target_entity TEXT,
  details JSONB DEFAULT '{}',
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE
);

-- =============================================
-- 4. SYSTEM ALERTS
-- Alerts generated by health checks
-- =============================================
CREATE TABLE IF NOT EXISTS public.system_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id UUID REFERENCES public.system_health_runs(id) ON DELETE SET NULL,
  severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  category TEXT NOT NULL DEFAULT 'system',
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  details JSONB DEFAULT '{}',
  acknowledged_at TIMESTAMP WITH TIME ZONE,
  acknowledged_by UUID REFERENCES auth.users(id),
  resolved_at TIMESTAMP WITH TIME ZONE,
  resolved_by UUID REFERENCES auth.users(id),
  resolution_notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- 5. APP ERROR EVENTS
-- Client and server error tracking
-- =============================================
CREATE TABLE IF NOT EXISTS public.app_error_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  source TEXT NOT NULL CHECK (source IN ('client', 'server', 'edge_function', 'webhook')),
  severity TEXT NOT NULL DEFAULT 'error' CHECK (severity IN ('debug', 'info', 'warning', 'error', 'critical')),
  error_type TEXT,
  message TEXT NOT NULL,
  stack_hash TEXT,
  stack_trace TEXT,
  component TEXT,
  metadata JSONB DEFAULT '{}',
  device_info JSONB DEFAULT '{}',
  session_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- 6. JOB EVENTS
-- Queue job tracking
-- =============================================
CREATE TABLE IF NOT EXISTS public.job_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  queue_name TEXT NOT NULL,
  job_type TEXT NOT NULL,
  job_id TEXT,
  status TEXT NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'dead_letter')),
  priority INTEGER DEFAULT 0,
  attempts INTEGER DEFAULT 0,
  max_attempts INTEGER DEFAULT 3,
  last_error TEXT,
  payload_hash TEXT,
  metadata JSONB DEFAULT '{}',
  scheduled_for TIMESTAMP WITH TIME ZONE,
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- 7. SYSTEM CONFIGURATION
-- Runtime configuration flags (e.g., circuit breakers)
-- =============================================
CREATE TABLE IF NOT EXISTS public.system_config (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}',
  description TEXT,
  updated_by UUID REFERENCES auth.users(id),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- INDEXES
-- =============================================
CREATE INDEX IF NOT EXISTS idx_system_health_runs_started_at ON public.system_health_runs(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_health_runs_status ON public.system_health_runs(status);
CREATE INDEX IF NOT EXISTS idx_system_health_checks_run_id ON public.system_health_checks(run_id);
CREATE INDEX IF NOT EXISTS idx_system_health_checks_status ON public.system_health_checks(status);
CREATE INDEX IF NOT EXISTS idx_system_actions_run_id ON public.system_actions(run_id);
CREATE INDEX IF NOT EXISTS idx_system_actions_status ON public.system_actions(status);
CREATE INDEX IF NOT EXISTS idx_system_alerts_severity ON public.system_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_system_alerts_resolved ON public.system_alerts(resolved_at) WHERE resolved_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_app_error_events_user_id ON public.app_error_events(user_id);
CREATE INDEX IF NOT EXISTS idx_app_error_events_created_at ON public.app_error_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_error_events_severity ON public.app_error_events(severity);
CREATE INDEX IF NOT EXISTS idx_app_error_events_stack_hash ON public.app_error_events(stack_hash);
CREATE INDEX IF NOT EXISTS idx_job_events_queue_name ON public.job_events(queue_name);
CREATE INDEX IF NOT EXISTS idx_job_events_status ON public.job_events(status);
CREATE INDEX IF NOT EXISTS idx_job_events_created_at ON public.job_events(created_at DESC);

-- =============================================
-- ENABLE RLS ON ALL TABLES
-- =============================================
ALTER TABLE public.system_health_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_health_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_error_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_config ENABLE ROW LEVEL SECURITY;

-- =============================================
-- RLS POLICIES - Admin Only Access
-- =============================================

-- Helper function to check if user is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.users 
    WHERE id = auth.uid() AND is_admin = TRUE
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- system_health_runs: Admin read-only
CREATE POLICY "Admin read system_health_runs" ON public.system_health_runs
  FOR SELECT USING (public.is_admin());

CREATE POLICY "Service role full access system_health_runs" ON public.system_health_runs
  FOR ALL USING (auth.role() = 'service_role');

-- system_health_checks: Admin read-only
CREATE POLICY "Admin read system_health_checks" ON public.system_health_checks
  FOR SELECT USING (public.is_admin());

CREATE POLICY "Service role full access system_health_checks" ON public.system_health_checks
  FOR ALL USING (auth.role() = 'service_role');

-- system_actions: Admin read-only
CREATE POLICY "Admin read system_actions" ON public.system_actions
  FOR SELECT USING (public.is_admin());

CREATE POLICY "Service role full access system_actions" ON public.system_actions
  FOR ALL USING (auth.role() = 'service_role');

-- system_alerts: Admin read/update (for acknowledgment)
CREATE POLICY "Admin read system_alerts" ON public.system_alerts
  FOR SELECT USING (public.is_admin());

CREATE POLICY "Admin update system_alerts" ON public.system_alerts
  FOR UPDATE USING (public.is_admin());

CREATE POLICY "Service role full access system_alerts" ON public.system_alerts
  FOR ALL USING (auth.role() = 'service_role');

-- app_error_events: Users can insert their own, admin can read all
CREATE POLICY "Users insert own errors" ON public.app_error_events
  FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Admin read all errors" ON public.app_error_events
  FOR SELECT USING (public.is_admin());

CREATE POLICY "Service role full access app_error_events" ON public.app_error_events
  FOR ALL USING (auth.role() = 'service_role');

-- job_events: Admin read-only
CREATE POLICY "Admin read job_events" ON public.job_events
  FOR SELECT USING (public.is_admin());

CREATE POLICY "Service role full access job_events" ON public.job_events
  FOR ALL USING (auth.role() = 'service_role');

-- system_config: Admin read/update
CREATE POLICY "Admin read system_config" ON public.system_config
  FOR SELECT USING (public.is_admin());

CREATE POLICY "Admin update system_config" ON public.system_config
  FOR UPDATE USING (public.is_admin());

CREATE POLICY "Service role full access system_config" ON public.system_config
  FOR ALL USING (auth.role() = 'service_role');

-- =============================================
-- TRIGGERS
-- =============================================

-- Auto-update updated_at for job_events
CREATE OR REPLACE FUNCTION update_job_events_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_job_events_updated_at
  BEFORE UPDATE ON public.job_events
  FOR EACH ROW
  EXECUTE FUNCTION update_job_events_updated_at();

-- =============================================
-- INITIAL SYSTEM CONFIG VALUES
-- =============================================
INSERT INTO public.system_config (key, value, description) VALUES
  ('circuit_breaker_openfoodfacts', '{"enabled": false, "failure_threshold": 5, "reset_timeout_ms": 60000}', 'Circuit breaker for Open Food Facts API'),
  ('circuit_breaker_upcitemdb', '{"enabled": false, "failure_threshold": 5, "reset_timeout_ms": 60000}', 'Circuit breaker for UPC Item DB API'),
  ('maintenance_mode', '{"enabled": false, "message": ""}', 'Global maintenance mode flag'),
  ('rate_limits', '{"api_requests_per_minute": 60, "scans_per_minute": 10}', 'Rate limiting configuration'),
  ('health_check_schedule', '{"daily_cron": "0 2 * * *", "hourly_light": true}', 'Health check scheduling configuration')
ON CONFLICT (key) DO NOTHING;

-- =============================================
-- HELPER FUNCTIONS
-- =============================================

-- Function to create a new health run
CREATE OR REPLACE FUNCTION public.start_health_run(
  p_environment TEXT DEFAULT 'production',
  p_trigger_type TEXT DEFAULT 'scheduled',
  p_triggered_by UUID DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
  v_run_id UUID;
BEGIN
  INSERT INTO public.system_health_runs (environment, trigger_type, triggered_by)
  VALUES (p_environment, p_trigger_type, p_triggered_by)
  RETURNING id INTO v_run_id;
  
  RETURN v_run_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to complete a health run
CREATE OR REPLACE FUNCTION public.complete_health_run(
  p_run_id UUID,
  p_status TEXT,
  p_summary TEXT DEFAULT NULL
)
RETURNS VOID AS $$
BEGIN
  UPDATE public.system_health_runs
  SET 
    finished_at = NOW(),
    status = p_status,
    summary_text = p_summary
  WHERE id = p_run_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to log a health check result
CREATE OR REPLACE FUNCTION public.log_health_check(
  p_run_id UUID,
  p_check_name TEXT,
  p_category TEXT,
  p_status TEXT,
  p_duration_ms INTEGER DEFAULT NULL,
  p_details JSONB DEFAULT '{}',
  p_error_message TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
  v_check_id UUID;
BEGIN
  INSERT INTO public.system_health_checks (run_id, check_name, check_category, status, duration_ms, details, error_message)
  VALUES (p_run_id, p_check_name, p_category, p_status, p_duration_ms, p_details, p_error_message)
  RETURNING id INTO v_check_id;
  
  RETURN v_check_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to log a system action
CREATE OR REPLACE FUNCTION public.log_system_action(
  p_run_id UUID,
  p_action_name TEXT,
  p_action_type TEXT,
  p_status TEXT,
  p_target_entity TEXT DEFAULT NULL,
  p_details JSONB DEFAULT '{}',
  p_error_message TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
  v_action_id UUID;
BEGIN
  INSERT INTO public.system_actions (run_id, action_name, action_type, status, target_entity, details, error_message, completed_at)
  VALUES (
    p_run_id, 
    p_action_name, 
    p_action_type, 
    p_status, 
    p_target_entity, 
    p_details, 
    p_error_message,
    CASE WHEN p_status IN ('success', 'failed', 'skipped') THEN NOW() ELSE NULL END
  )
  RETURNING id INTO v_action_id;
  
  RETURN v_action_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to create an alert
CREATE OR REPLACE FUNCTION public.create_system_alert(
  p_run_id UUID,
  p_severity TEXT,
  p_title TEXT,
  p_message TEXT,
  p_details JSONB DEFAULT '{}'
)
RETURNS UUID AS $$
DECLARE
  v_alert_id UUID;
BEGIN
  INSERT INTO public.system_alerts (run_id, severity, title, message, details)
  VALUES (p_run_id, p_severity, p_title, p_message, p_details)
  RETURNING id INTO v_alert_id;
  
  RETURN v_alert_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to log an error event
CREATE OR REPLACE FUNCTION public.log_error_event(
  p_source TEXT,
  p_severity TEXT,
  p_message TEXT,
  p_user_id UUID DEFAULT NULL,
  p_error_type TEXT DEFAULT NULL,
  p_stack_hash TEXT DEFAULT NULL,
  p_component TEXT DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}',
  p_device_info JSONB DEFAULT '{}'
)
RETURNS UUID AS $$
DECLARE
  v_event_id UUID;
BEGIN
  INSERT INTO public.app_error_events (
    user_id, source, severity, error_type, message, 
    stack_hash, component, metadata, device_info
  )
  VALUES (
    p_user_id, p_source, p_severity, p_error_type, p_message,
    p_stack_hash, p_component, p_metadata, p_device_info
  )
  RETURNING id INTO v_event_id;
  
  RETURN v_event_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================
-- GRANT EXECUTE ON FUNCTIONS
-- =============================================
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.start_health_run(TEXT, TEXT, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_health_run(UUID, TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.log_health_check(UUID, TEXT, TEXT, TEXT, INTEGER, JSONB, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.log_system_action(UUID, TEXT, TEXT, TEXT, TEXT, JSONB, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_system_alert(UUID, TEXT, TEXT, TEXT, JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.log_error_event(TEXT, TEXT, TEXT, UUID, TEXT, TEXT, TEXT, JSONB, JSONB) TO authenticated, service_role;
